# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: hermes
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod download
builds:
  - # Builds macOS, Windows, and Linux versions
    env:
      - CGO_ENABLED=0
    binary: hermes
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    main: ./cmd/cli
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
